# Generated by Django 5.2.2 on 2025-06-08 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('kilometers_per_week', models.FloatField(help_text='Average kilometers driven per week')),
                ('electricity_per_month', models.FloatField(help_text='Electricity usage in kWh per month')),
                ('short_flights_per_year', models.IntegerField()),
                ('long_flights_per_year', models.IntegerField()),
                ('recycling', models.BooleanField(help_text='Does the user recycle?')),
                ('diet_type', models.CharField(choices=[('omnivore', 'Omnivore'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], max_length=20)),
                ('total_emissions', models.FloatField(blank=True, help_text='Calculated carbon footprint in kg/year', null=True)),
                ('classification', models.CharField(blank=True, help_text='Low / Average / High', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
